# Generated by Django 5.2.5 on 2025-08-29 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد محصول')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت واحد')),
                ('quantity', models.IntegerField(default=0, verbose_name='موجودی')),
                ('minimum_stock', models.IntegerField(default=0, verbose_name='حداقل موجودی')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='دسته\u200cبندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='InventoryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('total_products', models.IntegerField(default=0, verbose_name='تعداد کل محصولات')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='ارزش کل انبار')),
                ('low_stock_products', models.IntegerField(default=0, verbose_name='محصولات کم موجودی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'آمار انبار',
                'verbose_name_plural': 'آمار انبار',
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'ورود'), ('out', 'خروج'), ('adjustment', 'تعدیل')], max_length=20, verbose_name='نوع تراکنش')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت واحد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='شماره مرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تراکنش انبار',
                'verbose_name_plural': 'تراکنش\u200cهای انبار',
            },
        ),
    ]
