# Generated by Django 5.2.5 on 2025-08-29 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام حساب')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='شماره حساب')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مانده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'حساب\u200cها',
            },
        ),
        migrations.CreateModel(
            name='OngoingDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor_name', models.CharField(max_length=200, verbose_name='نام طلبکار')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('partial_paid', 'پرداخت جزئی'), ('paid', 'پرداخت شده')], default='pending', max_length=50, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بدهی در جریان',
                'verbose_name_plural': 'بدهی\u200cهای در جریان',
            },
        ),
        migrations.CreateModel(
            name='PayableCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.CharField(max_length=50, verbose_name='شماره چک')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ')),
                ('payee', models.CharField(max_length=200, verbose_name='گیرنده')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('status', models.CharField(choices=[('issued', 'صادر شده'), ('paid', 'پرداخت شده'), ('returned', 'برگشت خورده')], default='issued', max_length=50, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'چک پرداختی',
                'verbose_name_plural': 'چک\u200cهای پرداختی',
            },
        ),
        migrations.CreateModel(
            name='ReceivableCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.CharField(max_length=50, verbose_name='شماره چک')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ')),
                ('payer', models.CharField(max_length=200, verbose_name='پرداخت کننده')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('status', models.CharField(choices=[('received', 'دریافت شده'), ('deposited', 'واریز شده'), ('returned', 'برگشت خورده')], default='received', max_length=50, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'چک دریافتی',
                'verbose_name_plural': 'چک\u200cهای دریافتی',
            },
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مغایرت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('resolved', 'حل شده'), ('rejected', 'رد شده')], default='pending', max_length=50, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.account', verbose_name='حساب')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'مغایرت',
                'verbose_name_plural': 'مغایرت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پیگیری')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('customer_name', models.CharField(max_length=200, verbose_name='نام مشتری')),
                ('follow_up_date', models.DateField(verbose_name='تاریخ پیگیری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده')], default='pending', max_length=50, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'پیگیری',
                'verbose_name_plural': 'پیگیری\u200cها',
            },
        ),
        migrations.CreateModel(
            name='OverdueAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='نام مشتری')),
                ('overdue_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ معوقه')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('contact_info', models.TextField(blank=True, verbose_name='اطلاعات تماس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.account', verbose_name='حساب')),
            ],
            options={
                'verbose_name': 'حساب معوقه',
                'verbose_name_plural': 'حساب\u200cهای معوقه',
            },
        ),
    ]
